### ISSUE TITLE
direnv support

### ISSUE THREAD

**Issue by zimbatm** [acaloiaro/ess#1]
> Currently, this hook only supports .env files with environment variables of the form VAR_NAME=VAR_VALUE. [Direnv](https://direnv.net/)-style .envrc is not currently supported. Pull requests welcome!

Hi, cool project. I thought I would chime in since I'm the author of direnv.

The `.envrc` format is full bash, so it will be difficult to support. But you can tell direnv users to use the [`dotenv` stdlib function](https://direnv.net/man/direnv-stdlib.1.html#codedotenv-ltdotenvpathgtcode) to load the `.env` file, and become compatible with this project. It's one more file in the repo but I think it's worth it.

**Comment by acaloiaro** [comment]
Good idea, thanks. 

Since I'd like to add support for more `env` file formats, and hooks managers, this will be a good next step.

**Comment by acaloiaro** [comment]
I went ahead and updated `README` with these details. Thanks for the comment.
