### ISSUE TITLE
Hash mismatch when running ess through nix

### ISSUE THREAD

**Issue by meatcar** [acaloiaro/ess#12]
```
$ nix run github:acaloiaro/ess
error: hash mismatch in fixed-output derivation '/nix/store/58i7x5rjiiqyzc1h1p7ailkh8yni3nfv-ess-20231009-go-modules.drv':
         specified: sha256-Nxx88tK4bNg4kMXjamJZZLxWs/zPkI9Ukp9ATaBxo5o=
            got:    sha256-nnJCCKzlKIZmNBSrX9FejDHCvhSdChepQU9Pl0hbIaw=
error: 1 dependencies of derivation '/nix/store/92bd1fsq73vn7xj0kk931afvxfacfp1y-ess-20231009.drv' failed to build
```

Looks like https://github.com/acaloiaro/ess/commit/e46d3e4803cd6dbe2354d6fafa14624cd6de35d9 set an incorrect hash? 

Using https://github.com/nix-community/gomod2nix to pin vendor versions directly would eliminate the need for `vendorSha256`. I can throw together a PR if you'd like.

**Comment by acaloiaro** [comment]
Hey please do put one together if you don’t mind. Happy to merge a fix!

On Thu, Nov 16, 2023, at 19:27, Denys Pavlov wrote:
> 
> 
> `$ nix run github:acaloiaro/ess
> error: hash mismatch in fixed-output derivation '/nix/store/58i7x5rjiiqyzc1h1p7ailkh8yni3nfv-ess-20231009-go-modules.drv':
>          specified: sha256-Nxx88tK4bNg4kMXjamJZZLxWs/zPkI9Ukp9ATaBxo5o=
>             got:    sha256-nnJCCKzlKIZmNBSrX9FejDHCvhSdChepQU9Pl0hbIaw=
> error: 1 dependencies of derivation '/nix/store/92bd1fsq73vn7xj0kk931afvxfacfp1y-ess-20231009.drv' failed to build
`

**Comment by acaloiaro** [comment]
Thanks for opening the issue! @meatcar
